const ADD_TO_WATCH_LATER = "ADD_TO_WATCH_LATER";
const REMOVE_FROM_WATCH_LATER = "REMOVE_FROM_WATCH_LATER";
const INITIALIZE_WATCH_LATER = "INITIALIZE_WATCH_LATER";

export { ADD_TO_WATCH_LATER, REMOVE_FROM_WATCH_LATER, INITIALIZE_WATCH_LATER };
