const FILM_VIDEO_REQUEST = "FILM_VIDEO_REQUEST";
const FILM_VIDEO_SUCCESS = "FILM_VIDEO_SUCCESS";
const FILM_VIDEO_FAIL = "FILM_VIDEO_FAIL";

export { FILM_VIDEO_REQUEST, FILM_VIDEO_SUCCESS, FILM_VIDEO_FAIL };
