export const extraLarge = '@media (min-width: 1200px)'
export const large = '@media (min-width: 992px) and (max-width: 1199px)'
export const medium = '@media (min-width: 768px) and (max-width: 992px)'
export const small = '@media (min-width: 301px) and (max-width: 767px)' 
export const ultraSmall = '@media (max-width: 300px)'