const FILM_INFO_REQUEST = "FILM_INFO_REQUEST";
const FILM_INFO_SUCCESS = "FILM_INFO_SUCCESS";
const FILM_INFO_FAIL = "FILM_INFO_FAIL";

export { FILM_INFO_REQUEST, FILM_INFO_SUCCESS, FILM_INFO_FAIL };
