export const DISCOVER_REQUEST = "DISCOVER_REQUEST";
export const DISCOVER_SUCCESS = "DISCOVER_SUCCES";
export const DISCOVER_FAIL = "DISCOVER_FAIL";
export const GET_DISCOVER = "GET_DISCOVER";
export const GET_SEARCH_FILMS = "GET_SEARCH_FILMS";
