const DISCOVER_REQUEST = "DISCOVER_REQUEST";
const DISCOVER_SUCCESS = "DISCOVER_SUCCES";
const DISCOVER_FAIL = "DISCOVER_FAIL";
const GET_DISCOVER = "GET_DISCOVER";
const GET_SEARCH_FILMS = "GET_SEARCH_FILMS";

export {
  DISCOVER_REQUEST,
  DISCOVER_SUCCESS,
  DISCOVER_FAIL,
  GET_DISCOVER,
  GET_SEARCH_FILMS,
};
